"""Negotiate controller — buyer ↔ seller negotiation protocol.

These are buyer-facing protocol endpoints. Auth is EIP-191 signed by
the buyer (not the X-Admin-Key scheme). The signing requirement is
documented in the OpenAPI description; no FastAPI Security scheme applies.
"""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi_utils.cbv import cbv

import market_storefront.container as _container
from market_storefront.middleware import buyer_auth
from market_storefront.models.negotiation_models import (
    NegotiateContinueRequest,
    NegotiateContinueResponse,
    NegotiateNewRequest,
    NegotiateNewResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/negotiate", tags=["negotiate"])


@cbv(router)
class NegotiateController:
    def __init__(
        self,
        db=Depends(lambda: _container.resolved_sqlite_client),
    ) -> None:
        self._db = db

    @router.post(
        "/new",
        response_model=NegotiateNewResponse,
        summary="Start a new negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires EIP-191 signed "
            "`X-Signature` + `X-Timestamp` headers (generated by the buyer CLI)."
        ),
    )
    async def negotiate_new(
        self,
        body: NegotiateNewRequest,
        request: Request,
    ) -> NegotiateNewResponse:
        from market_storefront.utils.config import BASE_URL_OVERRIDE
        from market_storefront.utils.sync_negotiation import (
            OfferUnfulfillableError,
            StorefrontPausedError,
            start_sync_negotiation,
        )

        buyer_auth._verify(request, "negotiate_new", body.listing_id, body.buyer_address)
        authenticated_buyer = buyer_auth.settlement_buyer_identity(request, body.buyer_address)

        base_url = BASE_URL_OVERRIDE or ""
        try:
            result = await start_sync_negotiation(
                sqlite_client=self._db,
                our_listing_id=body.listing_id,
                buyer_address=body.buyer_address,
                provision_terms=body.provision_terms,
                proposal=body.proposal,
                our_base_url=base_url,
                their_agent_url=body.buyer_agent_url or body.buyer_address,
            )
            await self._db.bind_authenticated_negotiation_buyer(
                negotiation_id=result["negotiation_id"], buyer=authenticated_buyer,
            )
        except StorefrontPausedError as exc:
            raise HTTPException(status_code=503, detail={
                "error": "paused", "reason": exc.reason,
                "hint": "Storefront or listing is paused; use admin API to advance or resume",
            })
        except OfferUnfulfillableError as exc:
            raise HTTPException(status_code=409, detail={
                "error": "offer_unfulfillable",
                "reason": exc.reason,
                "listing_id": exc.listing_id,
                "hint": (
                    "Seller refused: listing is not in a state that can accept "
                    "new negotiations, or no matching compute is currently "
                    "available. Try a different listing."
                ),
            })
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/new] %s", exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateNewResponse(**result)

    @router.post(
        "/{neg_id}",
        response_model=NegotiateContinueResponse,
        summary="Advance an existing negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires EIP-191 signed "
            "`X-Signature` + `X-Timestamp` headers."
        ),
    )
    async def negotiate_continue(
        self,
        neg_id: str,
        body: NegotiateContinueRequest,
        request: Request,
    ) -> NegotiateContinueResponse:
        from market_storefront.utils.sync_negotiation import continue_sync_negotiation

        buyer_auth._verify(request, "negotiate_continue", neg_id, body.buyer_address)
        await buyer_auth.require_negotiation_owner(self._db, neg_id, body.buyer_address, request)

        if body.action == "counter" and body.proposal is None:
            raise HTTPException(status_code=400, detail="'proposal' required for counter")

        try:
            result = await continue_sync_negotiation(
                sqlite_client=self._db,
                neg_id=neg_id,
                buyer_action=body.action,
                buyer_proposal=body.proposal,
                buyer_reason=body.reason,
                buyer_address=body.buyer_address,
            )
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/%s] %s", neg_id, exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateContinueResponse(**result)
