"""Negotiate controller — buyer ↔ seller negotiation protocol.

These are buyer-facing protocol endpoints. Auth is EIP-191 signed by
the buyer (not the X-Admin-Key scheme). The signing requirement is
documented in the OpenAPI description; no FastAPI Security scheme applies.
"""
from __future__ import annotations

import logging
import asyncio
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi_utils.cbv import cbv

import market_storefront.container as _container
from market_storefront.middleware import buyer_auth
from market_storefront.models.negotiation_models import (
    NegotiateContinueRequest,
    NegotiateContinueResponse,
    NegotiateNewRequest,
    NegotiateNewResponse,
    CapacityHoldRequest,
    CapacityHoldActionRequest,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/negotiate", tags=["negotiate"])


@cbv(router)
class NegotiateController:
    def __init__(
        self,
        db=Depends(lambda: _container.resolved_sqlite_client),
    ) -> None:
        self._db = db

    @router.post('/{neg_id}/capacity-hold', summary='Reserve capacity before escrow payment')
    async def capacity_hold(self, neg_id: str, body: CapacityHoldRequest, request: Request) -> dict:
        from market_storefront.utils import capacity_holds
        from market_storefront.utils.config import CHAINS
        try:
            binding = capacity_holds.validate_binding(body.binding)
            capacity_holds.require(binding['negotiationId'] == neg_id and binding['buyer'] == body.buyer_address)
            # Existing auth signs resource identity, not the JSON body. Include
            # its canonical digest so original/config/payment bindings cannot be swapped.
            buyer_auth._verify(request, 'capacity_hold_reserve', neg_id + ':' + capacity_holds.digest(binding), body.buyer_address)
            await buyer_auth.require_negotiation_owner(self._db, neg_id, body.buyer_address, request)
            capacity_holds.require(getattr(CHAINS.get('base_sepolia'), 'chain_id', None) == 84532)
            result = await self._db.reserve_available_compute_vm(listing_id=binding['listingId'], capacity_hold_binding=binding)
            if not result:
                raise ValueError('capacity_hold_unavailable')
            return result
        except ValueError:
            raise HTTPException(status_code=409, detail='capacity_hold_unavailable') from None

    @router.get('/{neg_id}/capacity-hold/{hold_id}', summary='Observe retained capacity hold')
    async def capacity_hold_status(self, neg_id: str, hold_id: str, buyer_address: str, request: Request) -> dict:
        from market_storefront.utils import capacity_holds
        from market_storefront.utils.config import settings
        buyer_auth._verify(request, 'capacity_hold_status', neg_id + ':' + hold_id, buyer_address)
        await buyer_auth.require_negotiation_owner(self._db, neg_id, buyer_address, request)
        try:
            return await asyncio.to_thread(capacity_holds.transition, self._db, negotiation_id=neg_id,
                hold_id=hold_id, buyer=buyer_address.lower(), seller=(settings.wallet.address or '').lower(), action='status')
        except ValueError:
            raise HTTPException(status_code=409, detail='capacity_hold_unavailable') from None

    @router.post('/{neg_id}/capacity-hold/{hold_id}', summary='Arm once before payment, or cancel an unarmed hold')
    async def capacity_hold_action(self, neg_id: str, hold_id: str, body: CapacityHoldActionRequest, request: Request) -> dict:
        from market_storefront.utils import capacity_holds
        from market_storefront.utils.config import CHAINS, settings
        buyer_auth._verify(request, 'capacity_hold_' + body.action, neg_id + ':' + hold_id, body.buyer_address)
        await buyer_auth.require_negotiation_owner(self._db, neg_id, body.buyer_address, request)
        try:
            if body.action == 'arm':
                capacity_holds.require(getattr(CHAINS.get('base_sepolia'), 'chain_id', None) == 84532)
            return await asyncio.to_thread(capacity_holds.transition, self._db, negotiation_id=neg_id,
                hold_id=hold_id, buyer=body.buyer_address.lower(), seller=(settings.wallet.address or '').lower(), action=body.action)
        except ValueError:
            raise HTTPException(status_code=409, detail='capacity_hold_unavailable') from None

    @router.post(
        "/new",
        response_model=NegotiateNewResponse,
        summary="Start a new negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires EIP-191 signed "
            "`X-Signature` + `X-Timestamp` headers (generated by the buyer CLI)."
        ),
    )
    async def negotiate_new(
        self,
        body: NegotiateNewRequest,
        request: Request,
    ) -> NegotiateNewResponse:
        from market_storefront.utils.config import BASE_URL_OVERRIDE
        from market_storefront.utils.sync_negotiation import (
            OfferUnfulfillableError,
            StorefrontPausedError,
            start_sync_negotiation,
        )

        buyer_auth._verify(request, "negotiate_new", body.listing_id, body.buyer_address)
        authenticated_buyer = buyer_auth.settlement_buyer_identity(request, body.buyer_address)

        base_url = BASE_URL_OVERRIDE or ""
        try:
            result = await start_sync_negotiation(
                sqlite_client=self._db,
                our_listing_id=body.listing_id,
                buyer_address=body.buyer_address,
                provision_terms=body.provision_terms,
                proposal=body.proposal,
                our_base_url=base_url,
                their_agent_url=body.buyer_agent_url or body.buyer_address,
            )
            await self._db.bind_authenticated_negotiation_buyer(
                negotiation_id=result["negotiation_id"], buyer=authenticated_buyer,
            )
        except StorefrontPausedError as exc:
            raise HTTPException(status_code=503, detail={
                "error": "paused", "reason": exc.reason,
                "hint": "Storefront or listing is paused; use admin API to advance or resume",
            })
        except OfferUnfulfillableError as exc:
            raise HTTPException(status_code=409, detail={
                "error": "offer_unfulfillable",
                "reason": exc.reason,
                "listing_id": exc.listing_id,
                "hint": (
                    "Seller refused: listing is not in a state that can accept "
                    "new negotiations, or no matching compute is currently "
                    "available. Try a different listing."
                ),
            })
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/new] %s", exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateNewResponse(**result)

    @router.post(
        "/{neg_id}",
        response_model=NegotiateContinueResponse,
        summary="Advance an existing negotiation",
        description=(
            "Buyer-facing protocol endpoint. Requires EIP-191 signed "
            "`X-Signature` + `X-Timestamp` headers."
        ),
    )
    async def negotiate_continue(
        self,
        neg_id: str,
        body: NegotiateContinueRequest,
        request: Request,
    ) -> NegotiateContinueResponse:
        from market_storefront.utils.sync_negotiation import continue_sync_negotiation

        buyer_auth._verify(request, "negotiate_continue", neg_id, body.buyer_address)
        await buyer_auth.require_negotiation_owner(self._db, neg_id, body.buyer_address, request)

        if body.action == "counter" and body.proposal is None:
            raise HTTPException(status_code=400, detail="'proposal' required for counter")

        try:
            result = await continue_sync_negotiation(
                sqlite_client=self._db,
                neg_id=neg_id,
                buyer_action=body.action,
                buyer_proposal=body.proposal,
                buyer_reason=body.reason,
                buyer_address=body.buyer_address,
            )
        except ValueError as exc:
            raise HTTPException(status_code=404, detail=str(exc))
        except Exception as exc:
            logger.error("[NEGOTIATE/%s] %s", neg_id, exc, exc_info=True)
            raise HTTPException(status_code=500, detail=str(exc))
        return NegotiateContinueResponse(**result)
