"""Round-trip the service's Alkahest escrow codecs against compose Anvil."""
from __future__ import annotations

import time
from dataclasses import dataclass
from importlib import resources
from typing import Any

import pytest
from alkahest_py import AlkahestClient
from eth_account.signers.local import LocalAccount
from web3 import Web3

from service.clients.alkahest import (
    Erc1155NonTierableEscrowCodec,
    Erc1155TierableEscrowCodec,
    Erc721NonTierableEscrowCodec,
    Erc721TierableEscrowCodec,
    encode_recipient_demand,
    get_alkahest_network,
    get_recipient_arbiter,
    resolve_alkahest_address_config,
)
from src.settings import settings

pytestmark = pytest.mark.e2e_alkahest_escrow_codecs

_CHAIN_NAME = "anvil"
_ALKAHEST_ADDRESSES_PATH = str(
    resources.files("market_storefront.data").joinpath("alkahest_anvil_addresses.json")
)

# Mock token deployments from the baked Anvil state generated by
# test-env/generate_state.py. The ERC20 mock is already used by the deal e2e;
# these are the sibling mock NFT contracts from the same deterministic deploy.
_MOCK_ERC721_A = "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707"
_MOCK_ERC1155_A = "0x0165878a594ca255338adfa4d48449f69242eb8f"

# Standard Anvil account #0. It has ETH in the baked state and mock mint
# functions are public, so this keeps mint funding separate from the buyer.
_ANVIL_GOD_PRIVATE_KEY = (
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
)

_ERC721_ABI = [
    {
        "type": "function",
        "name": "mint",
        "stateMutability": "nonpayable",
        "inputs": [{"name": "to", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "approve",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "to", "type": "address"},
            {"name": "tokenId", "type": "uint256"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "balanceOf",
        "stateMutability": "view",
        "inputs": [{"name": "owner", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
    },
    {
        "type": "function",
        "name": "ownerOf",
        "stateMutability": "view",
        "inputs": [{"name": "tokenId", "type": "uint256"}],
        "outputs": [{"name": "", "type": "address"}],
    },
    {
        "type": "event",
        "name": "Transfer",
        "inputs": [
            {"indexed": True, "name": "from", "type": "address"},
            {"indexed": True, "name": "to", "type": "address"},
            {"indexed": True, "name": "tokenId", "type": "uint256"},
        ],
        "anonymous": False,
    },
]
_ERC1155_ABI = [
    {
        "type": "function",
        "name": "mint",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "to", "type": "address"},
            {"name": "id", "type": "uint256"},
            {"name": "amount", "type": "uint256"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "setApprovalForAll",
        "stateMutability": "nonpayable",
        "inputs": [
            {"name": "operator", "type": "address"},
            {"name": "approved", "type": "bool"},
        ],
        "outputs": [],
    },
    {
        "type": "function",
        "name": "balanceOf",
        "stateMutability": "view",
        "inputs": [
            {"name": "account", "type": "address"},
            {"name": "id", "type": "uint256"},
        ],
        "outputs": [{"name": "", "type": "uint256"}],
    },
]


@dataclass(frozen=True)
class CodecCase:
    name: str
    asset_kind: str
    codec: Any


_CODEC_CASES = [
    CodecCase("erc721-nontierable", "erc721", Erc721NonTierableEscrowCodec()),
    CodecCase("erc721-tierable", "erc721", Erc721TierableEscrowCodec()),
    CodecCase("erc1155-nontierable", "erc1155", Erc1155NonTierableEscrowCodec()),
    CodecCase("erc1155-tierable", "erc1155", Erc1155TierableEscrowCodec()),
]


def _field(obj: Any, *names: str) -> Any:
    for name in names:
        if isinstance(obj, dict) and name in obj:
            return obj[name]
        if hasattr(obj, name):
            return getattr(obj, name)
    raise AssertionError(f"none of fields {names!r} found on {obj!r}")


def _address(value: Any) -> str:
    return str(value).lower()


def _send_tx(w3: Web3, account: LocalAccount, tx: dict[str, Any]) -> Any:
    tx.setdefault("from", account.address)
    tx.setdefault("chainId", int(settings.RPC.CHAIN_ID))
    tx.setdefault("nonce", w3.eth.get_transaction_count(account.address))
    tx["gas"] = max(int(tx.get("gas", 0)), 500_000)
    if "maxFeePerGas" not in tx and "maxPriorityFeePerGas" not in tx:
        tx.setdefault("gasPrice", w3.eth.gas_price)
    signed = account.sign_transaction(tx)
    raw_tx = (
        signed.raw_transaction
        if hasattr(signed, "raw_transaction")
        else signed.rawTransaction
    )
    receipt = w3.eth.wait_for_transaction_receipt(
        w3.eth.send_raw_transaction(raw_tx), timeout=30
    )
    assert receipt.status == 1
    return receipt


def _mint_erc721(w3: Web3, buyer_address: str) -> int:
    account = w3.eth.account.from_key(_ANVIL_GOD_PRIVATE_KEY)
    token = w3.eth.contract(address=Web3.to_checksum_address(_MOCK_ERC721_A), abi=_ERC721_ABI)
    before = token.functions.balanceOf(Web3.to_checksum_address(buyer_address)).call()
    receipt = _send_tx(
        w3,
        account,
        token.functions.mint(Web3.to_checksum_address(buyer_address)).build_transaction(),
    )
    after = token.functions.balanceOf(Web3.to_checksum_address(buyer_address)).call()
    assert after == before + 1

    transfers = token.events.Transfer().process_receipt(receipt)
    token_id = int(transfers[-1]["args"]["tokenId"])
    assert _address(token.functions.ownerOf(token_id).call()) == _address(buyer_address)
    return token_id


def _mint_erc1155(w3: Web3, buyer_address: str, token_id: int, amount: int) -> None:
    account = w3.eth.account.from_key(_ANVIL_GOD_PRIVATE_KEY)
    token = w3.eth.contract(address=Web3.to_checksum_address(_MOCK_ERC1155_A), abi=_ERC1155_ABI)
    before = token.functions.balanceOf(Web3.to_checksum_address(buyer_address), token_id).call()
    _send_tx(
        w3,
        account,
        token.functions.mint(
            Web3.to_checksum_address(buyer_address), token_id, amount
        ).build_transaction(),
    )
    after = token.functions.balanceOf(Web3.to_checksum_address(buyer_address), token_id).call()
    assert after == before + amount


def _approve_tierable_escrow(
    case: CodecCase,
    w3: Web3,
    token_id: int,
) -> None:
    if getattr(case.codec, "tier_attr", None) != "tierable":
        return

    account = w3.eth.account.from_key(str(settings.BUYER.PRIVATE_KEY))
    spender = Web3.to_checksum_address(
        case.codec.resolve_address(_CHAIN_NAME, config_path=_ALKAHEST_ADDRESSES_PATH)
    )

    if case.asset_kind == "erc721":
        token = w3.eth.contract(
            address=Web3.to_checksum_address(_MOCK_ERC721_A), abi=_ERC721_ABI
        )
        _send_tx(w3, account, token.functions.approve(spender, token_id).build_transaction())
        return

    token = w3.eth.contract(address=Web3.to_checksum_address(_MOCK_ERC1155_A), abi=_ERC1155_ABI)
    _send_tx(w3, account, token.functions.setApprovalForAll(spender, True).build_transaction())


def _build_obligation_data(case: CodecCase, w3: Web3, case_index: int) -> dict[str, Any]:
    buyer_address = str(settings.BUYER.WALLET_ADDRESS)
    common = {
        "arbiter": get_recipient_arbiter(
            _CHAIN_NAME, config_path=_ALKAHEST_ADDRESSES_PATH
        ),
        "demand": encode_recipient_demand(str(settings.SELLER.WALLET_ADDRESS)),
    }

    if case.asset_kind == "erc721":
        token_id = _mint_erc721(w3, buyer_address)
        _approve_tierable_escrow(case, w3, token_id)
        return {
            **common,
            "token": _MOCK_ERC721_A,
            "tokenId": token_id,
        }

    token_id = 100 + case_index
    amount = 3 + case_index
    _mint_erc1155(w3, buyer_address, token_id=token_id, amount=amount)
    _approve_tierable_escrow(case, w3, token_id)
    return {
        **common,
        "token": _MOCK_ERC1155_A,
        "tokenId": token_id,
        "amount": amount,
    }


def _assert_obligation_matches(case: CodecCase, data: dict[str, Any], obligation: Any) -> None:
    if isinstance(obligation, dict) and "data" in obligation:
        obligation = obligation["data"]

    assert _address(_field(obligation, "token")) == _address(data["token"])
    assert int(_field(obligation, "token_id", "tokenId")) == int(data["tokenId"])
    assert _address(_field(obligation, "arbiter")) == _address(data["arbiter"])
    assert bytes(_field(obligation, "demand")) == bytes(data["demand"])

    if case.asset_kind == "erc1155":
        assert int(_field(obligation, "amount", "value")) == int(data["amount"])


@pytest.mark.parametrize(
    "case_index,case",
    list(enumerate(_CODEC_CASES)),
    ids=[case.name for case in _CODEC_CASES],
)
async def test_alkahest_escrow_codec_create_read(case_index: int, case: CodecCase) -> None:
    w3 = Web3(Web3.HTTPProvider(str(settings.RPC.URL)))
    assert w3.is_connected()

    address_config = resolve_alkahest_address_config(
        get_alkahest_network(_CHAIN_NAME), config_path=_ALKAHEST_ADDRESSES_PATH
    )
    client = AlkahestClient(
        private_key=str(settings.BUYER.PRIVATE_KEY),
        rpc_url=str(settings.BUYER.CHAIN_RPC_URL),
        address_config=address_config,
    )

    obligation_data = _build_obligation_data(case, w3, case_index)
    uid = await case.codec.create_obligation(
        client, obligation_data, expiration_unix=int(time.time()) + 3600
    )
    assert uid.startswith("0x")
    assert len(uid) == 66

    obligation = await case.codec.get_obligation(client, uid)
    _assert_obligation_matches(case, obligation_data, obligation)
