"""Storefront FastAPI application.

Mirrors provisioning-service/src/main.py:

* ``FastAPI(lifespan=lifespan)`` — resolves singletons, starts background tasks.
* ``app.include_router()`` for every controller router.
* Admin auth via FastAPI Security() on individual routers — no middleware.
* X-Admin-Key OpenAPI security scheme registered so Swagger renders the
  Authorize button.

Global pause state
------------------
``_GLOBALLY_PAUSED`` is the module-level flag read by
``sync_negotiation.start_sync_negotiation``.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.openapi.utils import get_openapi
from fastapi.responses import JSONResponse

import market_storefront.container as _container
import market_storefront.utils.config as storefront_config
from market_storefront.utils.config import AGENT_ID, settings
from market_storefront.utils.sqlite_client import get_sqlite_client

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Global pause flag
# ---------------------------------------------------------------------------

_GLOBALLY_PAUSED: bool = False

_INERT_READ_PATHS = frozenset(
    {
        "/health",
        "/api/v1/system/health",
        "/api/v1/system/status",
    }
)


def is_inert_mode() -> bool:
    return storefront_config.ACTIVATION_MODE == "inert"


def inert_request_allowed(method: str, path: str) -> bool:
    """Whether an HTTP request is within the inert observation surface."""
    return method.upper() in {"GET", "HEAD"} and path in _INERT_READ_PATHS


def is_globally_paused() -> bool:
    return is_inert_mode() or _GLOBALLY_PAUSED


def _set_globally_paused(value: bool) -> None:
    if is_inert_mode() and not value:
        raise RuntimeError("an inert storefront cannot be resumed")
    global _GLOBALLY_PAUSED
    _GLOBALLY_PAUSED = value


# ---------------------------------------------------------------------------
def run_serve(
    host: str = "0.0.0.0",
    port: int | None = None,
) -> None:
    """Launch uvicorn. Called by ``market-storefront serve``."""
    import uvicorn

    resolved_port = port if port is not None else settings.port
    uvicorn.run(app, host=host, port=resolved_port, root_path=settings.gateway.root_path)


# ---------------------------------------------------------------------------
# Lifespan
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(_: FastAPI):
    from market_storefront.agent import _startup_tasks
    from market_storefront.services import alkahest_service
    from market_storefront.services.listing_service import ListingService
    from market_storefront.services.negotiation_service import NegotiationService
    from market_storefront.services.system_service import SystemService

    sqlite_client = get_sqlite_client()
    if is_inert_mode():
        alkahest_clients = {}
        logger.warning(
            "[STARTUP] Inert activation mode: signer and chain clients are disabled"
        )
    else:
        alkahest_clients = alkahest_service.build_clients()

    if is_inert_mode():
        # The middleware denies every seller/buyer route in inert mode. Keep
        # their service objects absent as a second boundary so a future route
        # wiring mistake cannot inherit initialized action-capable services.
        listing_svc = None
        negotiation_svc = None
    else:
        listing_svc = ListingService(
            sqlite_client=sqlite_client,
            alkahest_clients=alkahest_clients,
        )
        negotiation_svc = NegotiationService(sqlite_client=sqlite_client)
    system_svc = SystemService(sqlite_client=sqlite_client, agent_id=AGENT_ID)

    _container.resolved_sqlite_client = sqlite_client
    _container.resolved_alkahest_clients = alkahest_clients
    _container.resolved_listing_service = listing_svc
    _container.resolved_negotiation_service = negotiation_svc
    _container.resolved_system_service = system_svc

    logger.info("[STARTUP] Singletons initialized")
    await _startup_tasks()
    logger.info("[STARTUP] Background tasks started")

    yield

    logger.info("[SHUTDOWN] Storefront shutting down")


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Arkhai Storefront",
    description=(
        "Seller-side storefront for the Arkhai compute marketplace.\n\n"
        "**Admin endpoints** require an `X-Admin-Key` header — use the "
        "🔒 Authorize button above to set it.\n\n"
        "**Buyer-facing endpoints** (`/api/v1/negotiate/*`, `/api/v1/settle/*`) "
        "require EIP-191 signed `X-Signature` + `X-Timestamp` headers; "
        "these are generated by the buyer CLI and are not standard OpenAPI auth schemes."
    ),
    version="1.0.0",
    lifespan=lifespan,
    root_path=settings.gateway.root_path,
    swagger_ui_parameters={"persistAuthorization": True},
)


@app.middleware("http")
async def enforce_activation_mode(request: Request, call_next):
    """Deny every non-observation route before handler/auth execution when inert."""
    if is_inert_mode() and not inert_request_allowed(
        request.method, request.url.path
    ):
        return JSONResponse(
            status_code=503,
            content={
                "error": "storefront_inert",
                "detail": (
                    "This storefront is running in inert observation mode; "
                    "seller and buyer actions are disabled."
                ),
                "activation_mode": "inert",
            },
            headers={"Cache-Control": "no-store"},
        )
    return await call_next(request)


def _custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    schema.setdefault("components", {})
    schema["components"]["securitySchemes"] = {
        "AdminKey": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Admin-Key",
            "description": "Admin API key — required for all /api/v1/admin/* endpoints.",
        }
    }
    # Inject the gateway path prefix as the OpenAPI server URL so Swagger UI
    # generates correct curl examples. The FastAPI app root_path above drives
    # the docs page's OpenAPI URL; this servers block drives "try it out".
    root_path = settings.gateway.root_path
    if root_path:
        schema["servers"] = [{"url": root_path}]
    app.openapi_schema = schema
    return schema


app.openapi = _custom_openapi

# Controller imports after module-level app exists.
from market_storefront.controllers.admin_controller import (  # noqa: E402
    router as admin_router,
)
from market_storefront.controllers.listings_controller import (  # noqa: E402
    admin_router as admin_listings_router,
)
from market_storefront.controllers.listings_controller import (  # noqa: E402
    router as listings_router,
)
from market_storefront.controllers.negotiate_controller import (  # noqa: E402
    router as negotiate_router,
)
from market_storefront.controllers.negotiations_controller import (  # noqa: E402
    router as negotiations_router,
)
from market_storefront.controllers.settle_controller import (  # noqa: E402
    admin_settle_router,
)
from market_storefront.controllers.settle_controller import (  # noqa: E402
    router as settle_router,
)
from market_storefront.controllers.system_controller import (  # noqa: E402
    router as system_router,
)

app.include_router(system_router)
app.include_router(admin_router)
app.include_router(listings_router)
app.include_router(admin_listings_router)
app.include_router(negotiations_router)
app.include_router(negotiate_router)
app.include_router(settle_router)
app.include_router(admin_settle_router)
